### DISCUSSION TITLE
Auth server URL isn't using configured port for redirect

### DISCUSSION THREAD

**Discussion by Lindenk** [sevensolutions/traefik-oidc-auth#146] [Q&A] [answered]
Hey all, I don't know if this is a bug or I'm configuring something wrong but I can't seem get traefik to properly redirect to my auth server with its port

I have traefik-oidc-auth configured like so (using the kanidm example):
```toml
[http.middlewares.service-auth.plugin.traefik-oidc-auth]
Scopes = ["openid", "profile"]
[http.middlewares.service-auth.plugin.traefik-oidc-auth.Provider]
ClientId = "group-name"
TokenValidation = "IdToken"
Url = "https://auth.redacted.com:1443/oauth2/openid/group-name"
UsePkce = true
```

And kanidm configured like so:
```yaml
---
class: account
class: memberof
class: oauth2_resource_server
class: oauth2_resource_server_basic
class: object
directmemberof: idm_all_accounts@auth.redacted.com
displayname: Group Name
es256_private_key_der: private_binary
memberof: idm_all_accounts@auth.redacted.com
name: group-name
oauth2_rs_basic_secret: hidden
oauth2_rs_origin: https://service.redacted.com/oidc/callback
oauth2_rs_origin_landing: https://service.redacted.com/
oauth2_rs_scope_map: group-name@auth.redacted.com {"email", "groups", "openid", "profile"}
oauth2_rs_token_key: hidden
oauth2_strict_redirect_uri: true
spn: group-name@auth.redacted.com
uuid: ...
```

When accessing `https://service.redacted.com` I'm redirected to:
```
https://auth.redacted.com/ui/oauth2?client_id=group-name&code_challenge=<hidden>&code_challenge_method=S256&redirect_uri=https%3A%2F%2Fservice.redacted.com%2Foidc%2Fcallback&response_type=code&scope=openid+profile&state=<hidden>
```

rather than `https://auth.redacted.com:1443/...`. Attempting to manually fix the url gives me a text response of `Failed to exchange auth code`

Is there something I didn't configure correctly?
