### DISCUSSION TITLE
Okta: Issue with passing Auth token to K8s dashboard

### DISCUSSION THREAD

**Discussion by chasty2** [sevensolutions/traefik-oidc-auth#165] [Q&A] [answered]
I am using Okta, and I am able to successfully authenticate and access the kubernetes dashboard using traefik-oidc-auth. However, I do not seem to be passing the 'Authorization' header to the site. Here is my middleware config:

```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oidc
  namespace: kubernetes-dashboard
spec:
  plugin:
    traefik-oidc-auth:
      LogLevel: DEBUG
      Secret: urn:k8s:secret:k8s-dashboard-middleware-oidc:MIDDLEWARE_SECRET
      CallbackUri: "https://my-site.com/oauth2/callback"
      Provider:
        Url: "https://provider.okta.com"
        ClientId: urn:k8s:secret:k8s-dashboard-middleware-oidc:CLIENT_ID
        ClientSecret: urn:k8s:secret:k8s-dashboard-middleware-oidc:CLIENT_SECRET
        TokenValidation: "IdToken"
      Scopes: ["openid", "profile", "email", "groups"]
      Headers:
        - Name: Authorization
          Value: "{{`Bearer {{ .accessToken }}`}}"
```

Am I missing something? Any help would be appreciated. I can provide my Traefik ingress if need be

**Comment by sevensolutions** [comment, marked as answer]
Hi @chasty2,
I'am not a kubernetes expert but did you also try removin the escape sequence? I think this is not needed here. It's only needed when using traefik's yaml configuration directly (file-based) because it also supports some templating.

So can you try:
```yml
Headers:
  - Name: Authorization
    Value: "Bearer {{ .accessToken }}"
 ```
