### ISSUE TITLE
🚀 FR: Allow rules for networks

### ISSUE THREAD

**Issue by alexdelprete** [sevensolutions/traefik-oidc-auth#100]
### Feature description

I am trying to migrate from traefik-forward-auth to this wonderful plugin (thanks for creating it). I use Zitadel as IdP.

I made it work fine, except for one thing:

- in my homelab, I want to authenticate only if the request comes from the WAN, I'm using the X-Real-Ip header to whitelist all local+docker networks. With traefik-forward-auth I used this rule config file:

```console
# Allow LAN1
rule.Allow-LAN1.action = allow
rule.Allow-LAN1.rule = HeadersRegexp(`X-Real-Ip`, `^10\.1\.`)
# Allow LAN2
rule.Allow-LAN2.action = allow
rule.Allow-LAN2.rule = HeadersRegexp(`X-Real-Ip`, `^192\.168\.`)
# Allow Docker Containers
rule.Allow-Docker-Net.action = allow
rule.Allow-Docker-Net.rule = HeadersRegexp(`X-Real-Ip`, `^172\.19\.`)
```

Would it be possible to implement something like that? Right now, I'm not able to switch to your plugin because of this missing feature.

Thanks.

### Pitch

Would be nice to have a config section (AllowedNetworks) in which we can add all subnets for which auth shouldn't be performed.

### Doing your homework

- [x] I have searched for similar feature requests and not found a similar one.

**Comment by sevensolutions** [comment]
Hi @alexdelprete,
thank you for raising this issue.
I like your idea but i think we should implement this similar to *traefik-oidc-auth* and not just for handling headers.
So i would call it "Conditional Authentication" or similar.

I looked a bit into the traefik source code on how they implemented the router-matching logic and they're using [this library](https://github.com/vulcand/predicate) for parsing and matching the rules. I think we can do something similar here.

**Comment by alexdelprete** [comment]
Ciao Daniel,

thank you so much for the positive feedback.

May I ask what you mean when you say "we should implement this similar to traefik-oidc-auth"?

**Comment by sevensolutions** [comment]
Oh sorry this was a typo.. Of course i meant "similar to traefik-forward-auth".

**Comment by alexdelprete** [comment]
Ok, I edited the pitch making it more generic.

So, a rule engine that parses a config file. Looks very promising. :)

**Comment by sevensolutions** [comment]
@alexdelprete i've started to play around with this and implemented a PoC on this branch:
https://github.com/sevensolutions/traefik-oidc-auth/tree/feature/conditional-auth

The idea is that you can supply a `BypassAuthenticationRule` like:
```
BypassAuthenticationRule: "Header(`cache-control`, `no-cache`) || HeaderRegexp(`X-Real-Ip`, `^172\\.18\\.`)"`
```

Feel free to play around if you want but it's still a bit of work to finish this completely.

**Comment by alexdelprete** [comment]
> The idea is that you can supply a `BypassAuthenticationRule` like:

Wow...that was fast Daniel. Thanks a lot.

So if I understand the example provided, I can add multiple rules through the OR operator, right?

What do you think about something like this:

```go
BypassAuthenticationRules:
  - Header(`cache-control`, `no-cache`)
  - HeaderRegexp(`X-Real-Ip`, `^172\\.18\\.`)
```

**Comment by alexdelprete** [comment]
I'm testing now, but I have mixed results. With some services the bypass works, with others I have intermittent 403 error, and with others I have 404.

I need to debug a little, I see in the new code you introduced some logging about the rule matching. Where do I find the plugin log? Is it part of the traefik.log or access.log?

**Comment by sevensolutions** [comment]
Hi Alessandro,
I had another much simpler idea when I went to bed yesterday.

Can't we simply use two traefik routers?

```yml
routers;
  appInternal:
    rule: "Host(`myapp.domain.com`)"
    service: myapp
    priority: 20
    middlewares: ["oidc-auth"]
  appPublic:
    rule: "Host(`myapp.domain.com`) && HeadersRegexp(`X-Real-Ip`, `^10\\.1\\.`) || HeadersRegexp(`X-Real-Ip`, `^172\\.19\\.`) || HeadersRegexp(`X-Real-Ip`, `^100\\.`) || HeadersRegexp(`X-Real-Ip`, `^127\\.0\\.`)"
    service: myapp
    priority: 30 # Higher priority and no auth middleware
```

**Comment by alexdelprete** [comment]
If you have LOTS of services (I have 50-60, but some of my friends even more), it means having to double each entry. Not practical/manageable.

The idea is that the plugin (I used traefik-forward-auth before) decides, based on rules, if it allows the connection or auth is needed.

My services are defined like this:

```yaml
    portainer:
      entryPoints:
        - websecure
      rule: Host(`portainer.domain.net`)
      middlewares:
        - secured-auth
      tls: {}
      service: portainer

    hass:
      entryPoints:
        - websecure
      rule: Host(`hass.domain.net`)
      middlewares:
        - secured-noauth
      tls: {}
      service: hass
```

The middlewares are grouped in a chain:

```yaml
    secured-auth:
      chain:
        middlewares:
          - default-allowlist
          - default-headers
          - cloudflare-realip
          - oidc-auth

    secured-noauth:
      chain:
        middlewares:
          - default-allowlist
          - default-headers
          - cloudflare-realip
```

For each service with oidc-auth, if someone or other services connect from the LAN, no auth should be needed. Identity should only be checked when connecting from outside the LAN.
