### ISSUE TITLE
Plugin failed after no network connection

### ISSUE THREAD

**Issue by adriaanh** [sevensolutions/traefik-oidc-auth#109]
Don't know if this should be in this repo, let me know when this is really something I should report to Traefik.

Last night, my internet provider had some repair work, so the network was unavailable for a few minutes. Traefik detected closed network connections on the entrypoints, and after that the plugin failed to load because it couldn't reach the Traefik server, disabling the plugin and I couldn't access the services anymore. With a restart of the container, everything was back again (as expected). I don't get why, when there is temporary no internet access, the plugin should fail - as I expect the plugin to keep working as it's already downloaded/used the plugin before?

<img width="1343" alt="Image" src="https://github.com/user-attachments/assets/31021d29-5f3b-4c1c-bd75-0bb19ceabb27" />

**Comment by sevensolutions** [comment]
Hi @adriaanh,

just by looking at the log output i would say this looks like a bug in Traefik maybe.
It looks like it tried to download the plugin again but couldn't.
I don't know why it's even trying that again because it should have downloaded on the first start. But unfortunately i don't know the exact behavior of Traefik here.

**Comment by alexdelprete** [comment]
Personally, I use [Local Mode](https://plugins.traefik.io/install) for plugins. It happened that a plugin repository had issues, and Traefik didn't start because of that. Since then, I use Local Mode for my plugins, I don't want my main homelab service to depend on a cloud repository.

**Comment by adriaanh** [comment]
Hi @sevensolutions , I think you're right and this is purely a Traefik issue. 
@alexdelprete  Would you be willing share your setup/configuration?

**Comment by alexdelprete** [comment]
> [@alexdelprete](https://github.com/alexdelprete) Would you be willing share your setup/configuration?

Sure. I just got back from work, let me have my dinner, a little time for my kids and wife, then when they go to bed, I'll gather all needed info. :)

Meanwhile, take a look at the documentation, it's pretty clear, see the Local Mode section in the page I linked previously.

**Comment by alexdelprete** [comment]
Here's the config...

In `docker-compose.yml` volumes section, you need to map a folder to the `/plugins-local` container's folder:

```yaml
volumes:
  - $PWD/traefik-data/plugins:/plugins-local:ro
```

In Traefik's Static Config you need to configure the localPlugin:

```yaml
experimental:
  localPlugins:
    traefik-oidc-auth:
      moduleName: github.com/sevensolutions/traefik-oidc-auth
```

In Traefik's dynamic config you need to configure the plugin as per docs:

```yaml
  oidc-auth:
    plugin:
      traefik-oidc-auth:
        LogLevel: DEBUG
        CallbackUri: "/oidc/callback"
        LogoutUri: "/oidc/logout"
        SessionCookie:
          Domain: ".domain.net"
        Provider:
          Url: "https://id.domain.net"
          ClientId: "12345678901234567890"
          UsePkce: true
        Scopes: ["openid", "profile", "email"]
        # Bypass Authentication if request comes from local host or networks
        BypassAuthenticationRule: "HeaderRegexp(`X-Real-Ip`, `^10\\.1\\.`) || HeaderRegexp(`X-Real-Ip`, `^172\\.`) || HeaderRegexp(`X-Real-Ip`, `^100\\.`) || HeaderRegexp(`X-Real-Ip`, `^127\\.0\\.`)"
        Headers:
          - Name: "X-Oidc-Username"
            Value: "{{`{{ .claims.preferred_username }}`}}"
          - Name: "X-Oidc-Subject"
            Value: "sub"
          - Name: "Authorization"
            Value: "{{`Bearer {{ .accessToken }}`}}"
```

Then you need to clone the plugin from the GH repository in the folder you mapped in docker-compose.yml. In my case, it's the ./traefik-data/plugins (the . means where docker-compose.yml file exists):

- `cd` in the directory where traefik's `docker-compose.yml` is
- Create the dir structure: `mkdir -p ./traefik-data/plugins/src/github.com/sevensolutions/`
- Go in the folder where plugins sources have to be created: `cd traefik-data/plugins/src/github.com/sevensolutions/`
- Clone the main repo: `git clone https://github.com/sevensolutions/traefik-oidc-auth.git`
- Ensure the resulting folder structure is like this, using this command: `tree -d`

```console
❯ tree -d
.
└── traefik-oidc-auth
    ├── e2e
    │   └── tests
    │       └── dex
    ├── logging
    ├── oidc
    ├── predicate
    ├── rules
    ├── session
    ├── utils
    ├── vendor
    │   └── github.com
    │       ├── golang-jwt
    │       │   └── jwt
    │       │       └── v5
    │       ├── google
    │       │   └── uuid
    │       └── spyzhov
    │           └── ajson
    │               └── internal
    └── website
        ├── docs
        │   ├── config-samples
        │   ├── getting-started
        │   └── identity-providers
        ├── src
        │   ├── css
        │   └── pages
        └── static
            └── img
```
- now cd into the sources folder: `cd ./traefik-oidc-auth`
- if you want to make sure everything is up-to-date, or when you want to upgrade to latest version, simply issue a pull command: `git pull`
- Now you have to restart traefik's container: `docker compose up -d --force-recreate --remove-orphans`

That's it. :)

Let me know how it goes...
