### ISSUE TITLE
🐛 Bug: refresh doesn't work when `.Provider.TokenValidation = IdToken`

### ISSUE THREAD

**Issue by Nitive** [sevensolutions/traefik-oidc-auth#124]
### Expected vs actual behavior

Error:
```
[ERROR] [traefik-oidc-auth] Failed to validate renewed session: token has invalid claims: token is expired
```

Which leads to a logout every time an access token expires

Probably we need to add `IdToken` to a session here
https://github.com/sevensolutions/traefik-oidc-auth/blob/8a46e4771d6a95a1c90cf75795bfdc49e6438b6b/session.go#L111-L114

### Environment and Version Numbers

- Traefik v3.3.4
- Plugin v0.10.0
- IDP: Keycloak 2.26

All running in Kubernetes, middeware configured like this:

<details>
<summary>Middleware configuration</summary>

```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: my-middleware
spec:
  plugin:
    oidc-auth:
      Authorization:
        AssertClaims:
        - AnyOf:
          - my-group
          Name: groups
      CookieNamePrefix: my_prefix
      Provider:
        ClientId: [REDACTED]
        ClientSecret: [REDACTED]
        Url: [REDACTED]
        UsePkce: true
        TokenValidation: IdToken // Works with Introspection
      Scopes:
      - openid
      - email
      - profile
      - groups
      - offline_access
      Secret: [REDACTED]
      SessionCookie:
        Domain: [REDACTED]
        MaxAge: 86400
        SameSite: lax
```

</details>

### Doing your homework

- [x] I have searched for similar bug reports and not found a similar one.
