### ISSUE TITLE
🐛 Bug: `crypto/aes: invalid key size` error when using valid 32-character secret

### ISSUE THREAD

**Issue by ArthurHuyghe** [sevensolutions/traefik-oidc-auth#126]
### Reproduction steps

1. Configure `traefik-oidc-auth` plugin in `traefik.yaml` with a 32-character secret generated from [it-tools.tech](https://it-tools.tech/token-generator?length=32) or even the default secret .
2. Pass the secret via environment variable `${POCKET_ID_SECRET}`.
3. Start Traefik with the plugin enabled.
4. Attempt to authenticate through the plugin.

**Config snippet:**
```yaml
Pocket-Id:
  plugin:
    traefik-oidc-auth:
      Secret: ${POCKET_ID_SECRET}
      Provider:
        ClientId: ${POCKET_ID_CLIENT_ID}
        ClientSecret: ${POCKET_ID_CLIENT_SECRET}
        Url: https://pocket-id.mydomain/
        TokenValidation: "IdToken"
        UsePkce: true
      Scopes:
        - openid
        - profile
        - email
        - groups
```

### Expected vs actual behavior

 The plugin should accept the 32-byte secret as valid for AES-256 and proceed with token encryption/decryption. Instead when I try to authenticate in an application I am greeted with the following message `Failed to exchange auth code` and the following error shows up in the container logs `[ERROR] [traefik-oidc-auth] Exchange Auth Code: crypto/aes: invalid key size 19`.

### Environment and Version Numbers

- Traefik v3.3.5
- Plugin version: v0.10.1
- Identity Provider (IDP): Pocket-ID v0.45
- Deployment: All services are running on Docker

### Doing your homework

- [x] I have searched for similar bug reports and not found a similar one.

**Comment by sevensolutions** [comment]
> To me this seems correct?

Thx, yes, seems to be correct and RSA / RS256 is definitely working.
I will try to reproduce it on my machine.

**Comment by sevensolutions** [comment]
Hmm, ok.. Unfortunately i cannot reproduce it. Seems to be working fine, also with PKCE enabled.
At least with the default secret.
But i think you're right and it might be a problem with the plugin secret.

In the method where the error is happening, the secret is used to decrypt the code verifier for PKCE.

Can you please try something and temporarily disable PKCE?
Does this make a difference?

**Comment by ArthurHuyghe** [comment]
I disabled PKCE both in pocket-id and the traefik-config, now when i try to authenticade, pocket-id doesnt even want to authenticate and shows `something went wrong`. In the pocket-id logs, `Axios error: /api/oidc/clients/$%7BPOCKET_ID_CLIENT_ID%7D/meta - Record not found` shows up and nothing in the traefik logs.

**Comment by sevensolutions** [comment]
Hmm… Maybe you need to clear the cookies or use a private browser session to test.
But i have another question: Is your secret containing special characters? And especially a backslash maybe?

**Comment by sevensolutions** [comment]
Oh.. i know what the problem is ^^
Count the number of characters of the string "${POCKET_ID_SECRET}".. Its 19..
So it's not using your environment variable but this text.

The secret doesn't support using environment variables yet.
For the others you need to use properties with `Env` suffix like `ClientSecretEnv`.

If you're using YAML for your configuration, then you can try to use traefiks native environment variable substitution like so:
```yml
Pocket-Id:
  plugin:
    traefik-oidc-auth:
      Secret: '{{ env "POCKET_ID_SECRET" }}'
      Provider:
        ClientIdEnv: "POCKET_ID_CLIENT_ID"
        ClientSecretEnv: "POCKET_ID_CLIENT_SECRET"
        Url: https://pocket-id.mydomain/
        TokenValidation: "IdToken"
        UsePkce: true
```
