### ISSUE TITLE
🚀 FR: Ability to chain initialization for the plugin

### ISSUE THREAD

**Issue by adrianipopescu** [sevensolutions/traefik-oidc-auth#131]
### Feature description

Allow a centralized definition for a middleware for an application, then allow reuse and expansion.

Example:
```
- traefik.enable=true
- traefik.docker.network=proxy
- traefik.http.routers.dozzle.rule=Host("${ENV_SD_1}.${ENV_DOMAIN}") && PathPrefix("/dozzle")
- traefik.http.routers.dozzle.entrypoints=https

# Override: custom headers for Dozzle
- traefik.http.middlewares.oidc-override-dozzle.plugin.traefik-oidc-auth.ForwardHeaders=true
- traefik.http.middlewares.oidc-override-dozzle.plugin.traefik-oidc-auth.ForwardHeaders.Claims.email=X-Dozzle-User
- traefik.http.middlewares.oidc-override-dozzle.plugin.traefik-oidc-auth.ForwardHeaders.IdTokenHeader=Authorization
- traefik.http.middlewares.oidc-override-dozzle.plugin.traefik-oidc-auth.ForwardHeaders.AuthorizationPrefix=Bearer 

- traefik.http.middlewares.oidc-dozzle-chain.chain.middlewares=oidc-auth@docker,oidc-override-dozzle@docker

- traefik.http.routers.dozzle.middlewares=oidc-dozzle-chain@docker

- traefik.http.services.dozzle.loadbalancer.server.port=8080
```

with the main declaration on traefik's container for example

```
      - traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.Secret=<secret>
      - traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.Provider.Url=<provider>
      - traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.Provider.ClientId=<clientid>
      - traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.Provider.ClientSecret=<secret>
      - traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.Scopes=openid,profile,email
```

### Pitch

In my use case this allows for simple homelab-wide oidc configuration, but also allow per-app header config.

Basically DRY and templating.

### Doing your homework

- [x] I have searched for similar feature requests and not found a similar one.

**Comment by sevensolutions** [comment]
Hi @adrianipopescu 

thx for creating this issue but unfortunately iam not sure if i understand that correctly.
So you want to split the configuration into two parts? A global, re-usable one and one for each service?
I think this doesn‘t work in traefik and is better discussed there but the closest thing you can do with this plugin is using some environment variables.

So you define some environment variables:
```
PROVIDER_URL=…
CLIENT_ID=…
CLIENT_SECRET=…
```
and then you refernce them using the `…Env` settings. Eg:
```
- traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.Provider.UrlEnv=PROVIDER_URL
- traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.Provider.ClientIdEnv=CLIENT_ID
- traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.Provider.ClientSecretEnv=CLIENT_SECRET
- traefik.http.middlewares.oidc-override-dozzle.plugin.traefik-oidc-auth.ForwardHeaders=true
- traefik.http.middlewares.oidc-override-dozzle.plugin.traefik-oidc-auth.ForwardHeaders.Claims.email=X-Dozzle-User
- traefik.http.middlewares.oidc-override-dozzle.plugin.traefik-oidc-auth.ForwardHeaders.IdTokenHeader=Authorization
- traefik.http.middlewares.oidc-override-dozzle.plugin.traefik-oidc-auth.ForwardHeaders.AuthorizationPrefix=Bearer
```
The only downside is that you still need to provide the settings but you can reuse the values.
Please note that iam also in the middle of reworking the config a bit so this may change with the next release. See #128

**Comment by adrianipopescu** [comment]
In principle it does support it, you can partly initialize a plugin then continue setting the other fields, but it's... beyond me how it'd work from a development perspective.

**Comment by cdanis** [comment]
@adrianipopescu I think there are simpler, better ways to do the thing that you want to do here.

One option:  you could use a YAML file configuration for those middlewares, and then use [YAML anchors + aliases](https://smcleod.net/2022/11/yaml-anchors-and-aliases/) to do this.

Another option: you can add some other plugins, and use trusted headers to pass data from the OIDC plugin to them.  This is what I do in my homelab to have different permissions for some services.

An example (customized for my environment, and in k8s CRD format; apologies, but it should be easy for you to adapt):

First, configure the OIDC plugin to emit headers to backends.  Customize this as you wish.  To explain a more complicated example, the X-Oidc-Groups-Json is a [golang text/template](https://gobyexample.com/text-templates) that generates a correctly-quoted json string from arbitrary group names.

```yaml
  plugin:
    oidc:
      Authorization: {}
      Headers:
      - Name: X-Oidc-Username
        Value: '{{ .claims.preferred_username }}'
      - Name: X-Oidc-Superuser
        Value: '{{ with .claims.superuser }}{{.}}{{else}}null{{end}}'
      - Name: X-Oidc-Groups-Json
        Value: '[{{with .claims.groups}}{{range $idx, $g := .}}{{if $idx}},{{end}}"{{js $g}}"{{end}}{{end}}]'
```

Then, make sure you scrub these headers on all external requests, using Traefik's [built-in headers middleware](https://doc.traefik.io/traefik/middlewares/http/headers/):
```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: headers
spec:
  headers:
    browserXssFilter: true
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Oidc-Email: ""
      X-Oidc-Groups: ""
      X-Oidc-Groups-Json: ""
      X-Oidc-Name: ""
      X-Oidc-Superuser: ""
      X-Oidc-Username: ""
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
```

I attach this as a 'default' middleware on Traefik's external endpoints.  This ensures I can trust the headers in other Traefik middlewares and on my backend services.

Then, as an extra authorization layer for some services, you can use another simple [checkheaders plugin](https://plugins.traefik.io/plugins/628c9eda108ecc83915d7760/check-request-headers-plugin):

```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: superuser
spec:
  plugin:
    checkheaders:
      headers:
      - matchtype: one
        name: X-Oidc-Superuser
        values:
        - "yes"
```

And finally, to make it reusable, you simply [chain](https://doc.traefik.io/traefik/middlewares/http/chain/) the OIDC middleware and the above.
