### ISSUE TITLE
🚀 fr: AnyOf by container

### ISSUE THREAD

**Issue by PaddyPat** [sevensolutions/traefik-oidc-auth#152]
### Feature description

Hi,

As I see I could select the arrange allowed users To signin via oidc in the plugin section.

A nice feature would be to allow allof by container. The   attribute should be catches in every docker compose and allow access only users in oidc group ( admin group members can login in Traefik.domaon.com and users of group whoami can login if they are member of whoami (same clientid/secret in oidc plugin) but different docker compose files where they ref to the oidc plugin.

Hope you understand what I mean.
Br

### Doing your homework

- [x] I have searched for similar feature requests and not found a similar one.

**Comment by PaddyPat** [comment]
The plugin with id and secret is configured in Traefik.

Every container I will start, has the middleware oidc inside as label but there is no access management by container / label.

 I’m running a container gethhomepage with middleware oidc and another container filebrowser andd oidc middleware.

The oidc plugin checks only, if a user is confirmed by authelia / pocketid but I can’t change access rights per container.

It would be fine to add to every docker compose a tag oidc.allof=Group1 and only users inside Group1 can access this container.

**Comment by sevensolutions** [comment]
Unfortunately I'am still not sure if i'am following you correctly but when you're trying to use docker-labels to configure the middleware, something like this should do it:

```yml
services:
  service-1:
    # ...
    labels:
      - "traefik.http.routers.service-1-router.rule=Host(`service1.example.com`)"
      - "traefik.http.middlewares.oidc-auth-1.traefik-oidc-auth.provider.url=https://your-idp.com"
      - "traefik.http.middlewares.oidc-auth-1.traefik-oidc-auth.provider.clientId=..."
      - "traefik.http.middlewares.oidc-auth-1.traefik-oidc-auth.provider.clientSecret=..."
      - "traefik.http.middlewares.oidc-auth-1.traefik-oidc-auth.provider.authorization.assertClaims[0].name=groups"
      - "traefik.http.middlewares.oidc-auth-1.traefik-oidc-auth.provider.authorization.assertClaims[0].allOf=Group1"
      - "traefik.http.routers.service-1-router.middlewares=oidc-auth-1@docker"
  service-2:
    # ...
    labels:
      - "traefik.http.routers.service-2-router.rule=Host(`service2.example.com`)"
      - "traefik.http.middlewares.oidc-auth-2.traefik-oidc-auth.provider.url=https://your-idp.com"
      - "traefik.http.middlewares.oidc-auth-2.traefik-oidc-auth.provider.clientId=..."
      - "traefik.http.middlewares.oidc-auth-2.traefik-oidc-auth.provider.clientSecret=..."
      - "traefik.http.middlewares.oidc-auth-2.traefik-oidc-auth.provider.authorization.assertClaims[0].name=groups"
      - "traefik.http.middlewares.oidc-auth-2.traefik-oidc-auth.provider.authorization.assertClaims[0].allOf=Group2"
      - "traefik.http.routers.service-2-router.middlewares=oidc-auth-2@docker"
```
Disclaimer: I did not test that yet.

Each container (app) is then validating the token for the given group.
