### ISSUE TITLE
🐛 Bug: Logout using PocketID Not Working

### ISSUE THREAD

**Issue by egooner** [sevensolutions/traefik-oidc-auth#153]
### Reproduction steps

I am using v0.11.0 and Pocket-ID v1.2  and logout does not appear to be working!
I have the PocketID with multiple callback URLs configured 
```
POCKETID
https://app1.mydomain.com/oidc/callback
https://app2.mydomain.com/oidc/callback
https://app3.mydomain.com/oidc/callback
```
No other configuration other than secrets

In the Plugin configuration I have 
```
PLUGIN
http:
  middlewares:
    pocketid:
      plugin:
        traefik-oidc-auth:
          Secret: mysecret
          LogLevel: DEBUG
          CookieNamePrefix: TraefikPocketIdAuth
          Scopes:
            - openid
            - profile
            - email
          Provider:
            ClientId: myclientid
            ClientSecret: myclientsecret
            Url: "https://pocketid.mydomain.com/"
            TokenValidation: "IdToken"
          SessionCookie:
            Domain: ".mydomain.com"
            MaxAge: 10800           # 3 hours == 60 * 60 * 3 seconds
```

Login is working fine and if I issue app1.mydomain.com/logout - I get to the PocketID signout page and then after that I get presented with the PocketID login page .... if I ignore this and go to the app1.mydomain.com I expect to have to login again but am already logged in and the cookie is still present when using inspect.

### Expected vs actual behavior

Expected to logout and remove the cookie when trying to access again or require re-authentication

### Environment and Version Numbers

* Traefik 3.3.2
* Plugin  0.11.0
* PocketId 1.0

### Doing your homework

- [x] I have searched for similar bug reports and not found a similar one.
