### ISSUE TITLE
🚀 FR: Allow to check the session for every route

### ISSUE THREAD

**Issue by Sorio6** [sevensolutions/traefik-oidc-auth#168]
### Feature description

`CheckOnEveryRequest`

This feature forces a re-evaluation of a user session with each request, even if a valid session is already present.

By default, the session is reused as is. However, in scenarios where authorization rules are more advanced (such as Role-Based Access Control – RBAC) on nested paths or specific resources, the original behavior without double check can lead to certain middlewares being bypassed.

When `CheckOnEveryRequest` is enabled, each session is checked before accessing a route. I want to clarify that only the authorization is check, and there's no need to log in again after each route.

### Pitch

I'm using Docusaurus to serve documentation. However, some pages are sensitive and shouldn't be accessible to everyone.

Since Docusaurus doesn't support authentication, I've decided to rely on your Traefik plugin.

My need goes beyond simple authentication; I'd like to add role-based access control (RBAC) for certain pages.

The problem I'm facing is this: to access my documentation, I have one middleware running on `/docs` and a second one on `/docs/confidential`.

-  `/docs` requires authentication.
-   `/docs/confidential` requires the user to have the ADMIN authorization (role).

In the current state of the code, since `/docs/confidential` is included within `/docs`, a regular user can access the confidential document, and in the logs, I get "A session is present for the request and will be used."

### Doing your homework

- [x] I have searched for similar feature requests and not found a similar one.

**Comment by sevensolutions** [comment]
Hi @Sorio6,
thx for reporting this.

There might be another issue you may encounter when using Docusaurus. Docusaurus is an SPA which means that, once the page is loaded, navigations will be handled client-side.
So when the user navigates to `/docs` authorization will be checked, but if he then navigates to `/docs/confidential` this will be handled client-side and no request will be made to the middleware.

Did you find a solution for that because I have the same use-case.

**Comment by sevensolutions** [comment]
Thx for the explanations @gtheraud.

So if i understand that correctly, you're not using `npm run build` and then serve the static files using NGINX?

But anyway.. The more i think about this feature, the more it makes sense 😁
I think you have a config similar to:

```yml
http:
  middlewares:
    oidc-auth-user:
      plugin:
        traefik-oidc-auth:
          Authorization:
            AssertClaims:
              - Name: roles
                AnyOf: ["user"]
    oidc-auth-confidential:
      plugin:
        traefik-oidc-auth:
          Authorization:
            AssertClaims:
              - Name: roles
                AnyOf: ["superuser"]

  routers:
    docusaurus-all:
      entryPoints: ["web"]
      rule: "PathPrefix(`/docs`) || PathPrefix(`/oidc/callback`))"
      service: docusaurus
      middlewares: ["oidc-auth-user"]
    docusaurus-confidential:
      entryPoints: ["web"]
      rule: "PathPrefix(`/docs/confidential`)"
      service: docusaurus
      middlewares: ["oidc-auth-confidential"]
```

So we definitely need a way to check authorization on every request because they're using different middleware configurations.
