### ISSUE TITLE
🐛 Bug: Invalid code verifier when using with Pocket ID and PKCE enabled

### ISSUE THREAD

**Issue by ROODAY** [sevensolutions/traefik-oidc-auth#170]
### Reproduction steps

Trying to use this and Pocket ID to secure a wg-easy, but PKCE doesn't work. This is my docker compose yaml:
```
networks:
  proxy:
    name: proxy
    driver: bridge

services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    networks:
      - proxy
    volumes:
      - ./docker-data/traefik/letsencrypt:/letsencrypt
      - ./docker-data/traefik/http.yml:/http.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    command:
      - --accesslog=true
      - --providers.docker=true
      - --providers.file.filename=/http.yml
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.email=redacted
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
      - --experimental.plugins.traefik-oidc-auth.moduleName=github.com/sevensolutions/traefik-oidc-auth
      - --experimental.plugins.traefik-oidc-auth.version=v0.12.0

  wg-easy:
    environment:
      - LANG=en
      - WG_HOST=redacted
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    networks:
      - proxy
    volumes:
      - ./docker-data/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - traefik.enable=true
      - traefik.http.routers.wg.rule=Host(`redacted`)
      - traefik.http.services.wg.loadbalancer.server.port=51821
      - traefik.http.routers.wg.entrypoints=websecure
      - traefik.http.routers.wg.tls.certresolver=cloudflare
      - traefik.http.routers.wg.middlewares=oidc-auth@file
```

This is my traefik dynamic config:
```
http:
  middlewares:
    oidc-auth:
      plugin:
        traefik-oidc-auth:
          Secret: "redacted" # this is a 32 char alphanumeric string
          Provider:
            Url: "redacted"
            ClientId: "redacted"
            ClientSecret: "redacted"
            TokenValidation: "IdToken"
            UsePkce: true
          Scopes: ["openid", "profile", "email"]
```

When I enabled PKCE in Pocket ID OIDC client config, I get "Failed to exchange auth code" when I login, and in the traefik logs I see:
```
2025-06-24 03:44:33 [ERROR] [traefik-oidc-auth] exchangeAuthCode: received bad HTTP response from Provider: {"error":"Invalid code verifier"}
2025-06-24 03:44:33 [ERROR] [traefik-oidc-auth] Exchange Auth Code: invalid status code
```

Adding `UsePkce: true` in the middleware config didn't fix it.

### Expected vs actual behavior

Should've just worked, instead I see `Failed to exchange auth code`.

### Environment and Version Numbers

* Traefik 3.4.1
* Plugin v0.12.0
* IDP: Pocket ID
All running on Docker, Cloudflare SSL

### Log Output

```
2025-06-24 03:44:33 [ERROR] [traefik-oidc-auth] exchangeAuthCode: received bad HTTP response from Provider: {"error":"Invalid code verifier"}
2025-06-24 03:44:33 [ERROR] [traefik-oidc-auth] Exchange Auth Code: invalid status code
```

### Doing your homework

- [x] I have searched for similar bug reports and not found a similar one.
