### ISSUE TITLE
Issue: No public Keys found with OIDC and Traefik Dashboard

### ISSUE THREAD

**Issue by phillf** [sevensolutions/traefik-oidc-auth#27]
I have configured a middleware with the traefik-oidc-auth plugin. I get the "no public keys" after successfully authenticating against Authentik SSO.

Just trying to put the dashboard behind behind authentication here. Yes, basicAuth was only there as a test when I was trying to figure out why middlewares weren't loading.

**Log Entries:**
```
2024-12-06 20:10:01 [ERROR] [traefik-oidc-auth] Failed reading state cookie: http: named cookie not present

2024-12-06 20:10:02 [ERROR] [traefik-oidc-auth] Returned token is not valid: no public Keys found
```

**config.yml:**
```
global:
  checknewversion: true                       # Periodically check if a new version has been released.
  sendanonymoususage: true                    # Periodically send anonymous usage statistics.

log:
  level: WARN

api:
  dashboard: true

serversTransport:
  insecureSkipVerify: true

entryPoints:
  https:
    address: ":443"                           # Create the HTTPS entrypoint on port 443

  metrics:
    address: ":8082"                           # Create the HTTP metrics entrypoint on port 8082

certificatesResolvers:
  dns-cloudflare-nti:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory #LE Production
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # LE Staging
      dnsChallenge:
        provider: cloudflare
        resolvers: 1.1.1.1:53,1.0.0.1:53
        delayBeforeCheck: 90
      email: (redacted)
      storage: /etc/traefik/acme.json

providers:
  docker:
    endpoint: "tcp://socket-proxy-traefik:2375"   # Listen to the UNIX Docker socket
    exposedByDefault: false                   # Only expose container that are explicitly enabled (using label traefik.enabled)
    network: "traefik-backend"                    # Default network to use for connections to all containers.
    watch: true                               # Watch Docker Swarm events
  file:
    filename: "/etc/traefik/configs/config.yml"       # Link to the dynamic configuration
    directory: "/etc/traefik/configs/dynamic"       # Link to the dynamic configuration
    watch: true  
  providersThrottleDuration: 10               # Configuration reload frequency

metrics:
  prometheus:
    manualRouting: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

experimental:
  plugins:
    traefik-oidc-auth:
      moduleName: "github.com/sevensolutions/traefik-oidc-auth"
      version: "v0.4.1"
```

**middlewares.yml:**
```
http:
  middlewares:
    traefik-auth:
      basicAuth:
        users:
          - "user:passwd"
    TraefikOIDC:
      plugin:
        traefik-oidc-auth:
          Provider:
            Url: "https://sso.example.com/application/o/traefik/"
            ClientId: "...."
            ClientSecret: "...."
          Scopes: ["openid", "profile", "email"]
          Authorization:
            AssertClaims:
              - Name: "roles"
                AllOf: ["Traefik - Admins"]
```
**docker-compose.yml:**
```
services:
  traefik:
    image: docker.io/library/traefik:v3.2.1
    container_name: traefik
    stdin_open: true
    tty: true
    command:
      - --configFile=/etc/traefik/configs/config.yml
    ports:
      - 443:443
    volumes:
      - traefik-dynamic:/etc/traefik
    environment:
      - CF_DNS_API_TOKEN=(redacted)
      - TZ=America/New_York
    networks:
      - traefik-backend
      - socket_proxy
    restart: unless-stopped
    labels:
      # Enable Traefik
      - "traefik.enable=true"

      # HTTP Router - traefik-secure
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`proxy.mydomain.com`)"
      - "traefik.http.routers.traefik-secure.tls.certresolver=dns-cloudflare-nti"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.routers.traefik-secure.middlewares=TraefikOIDC@file"

      # HTTP Router - traefik-stats
      - "traefik.http.routers.stats-traefik-secure.tls=true"
      - "traefik.http.routers.stats-traefik-secure.entrypoints=https"
      - "traefik.http.routers.stats-traefik-secure.rule=Host(`stats.proxy.mydomain.com`)"
      - "traefik.http.routers.stats-traefik-secure.service=prometheus@internal"

volumes:
  traefik-config:
    driver: local
  traefik-dynamic:
    driver: local

networks:
  traefik-backend:
    name: traefik-backend
  socket_proxy:
    name: socket_proxy
    external: true
```

**Comment by sevensolutions** [comment]
Hi @phillf ,

i've not tested Authentik yet.
Can you please check what the JWKS endpoint is returning?

Acc. to [this documentation](https://docs.goauthentik.io/docs/add-secure-apps/providers/oauth2/) the URL should be in the form: `/application/o/<application slug>/jwks/`

It should return a json object with a `keys` array. What are the algorithms used in there?

**Comment by phillf** [comment]
When I hit the JWKS endpoint on mine I get the following:

`{}`

**Comment by phillf** [comment]
> When I hit the JWKS endpoint on mine I get the following:
> 
> `{}`

I set the certificate for the auth provider in Authentik and it actually returns a  key using RSA, RSA256.

```
kid	"d4413126fc50bc76e3b34d52707daf2e"
kty	"RSA"
alg	"RS256"
use	"sig"
n	"mAGtfZQ7huvQekxJBxuTkq3jOzf92rOUG9T0_3zX0ShGovkeb8Jy-NSIsJ66WJA8lGbK_gDvle_Qa2BueZwAKFXwwFx9oddyk5UnDN2uCc10lcwVb_ix3FAvGdqdy8O_heo_Mg63rEgEmSOUKKGC7Q61rLaKrdgnvFUFGJZn8zr6eoPHa7pIt4Cau_4TFAlYby7tCQfD4iFA-7yPTRDur-IR0jtYJMfq36oB9ZAdWxSCJRP0q_ZcVWZ0m9NIphNb1X9SdwLm6Sl_wZeK_uAXUNt5S_Mrz6Kk4fberMo9hcjpNJh-TU4rqJtE6j9YX6Y2f5-auenBQT_LpvUle3sLZQT9o5GYARV2T_w5sTDM7Nke4L8X94z2SxM9oIgKUMcZMxdEvDkV1zQwdJl7YyPFhWPaPFrzGs9p3_4jc2AV9cGVx76rKAXx7lgcKwcxFui3nfOrgxA2lpZjiiijywjdrr1qMSIpFZxNOVR12_m669pX-aELsw29NvWBK9arx7-7atnt734twLHZfZ9JhTNBqBt5Wl19ttD6V8a3UoKhLlFaM7bwuFvC_Yl0PopgRlRArpCGqskrZ0Ziwx_J659dkBbY-5Wl2BIUWT5ubbzNh2zeB7WT8kYlP77EvlVWF4wd_z-Sux2LSUbKkE2gjI-BwCpzqr8KnSiRQBH0wVLYIRs"
e	"AQAB"
x5c	
0	"MIIFUjCCAzqgAwIBAgIQGNiWoGGmTQWUKqS8CuwbYTANBgkqhkiG9w0BAQsFADAdMRswGQYDVQQDDBJhdXRoZW50aWsgMjAyNC4yLjIwHhcNMjQwNDA1MTM1NDA4WhcNMjUwNDA2MTM1NDA4WjBWMSowKAYDVQQDDCFhdXRoZW50aWsgU2VsZi1zaWduZWQgQ2VydGlmaWNhdGUxEjAQBgNVBAoMCWF1dGhlbnRpazEUMBIGA1UECwwLU2VsZi1zaWduZWQwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCYAa19lDuG69B6TEkHG5OSreM7N/3as5Qb1PT/fNfRKEai+R5vwnL41IiwnrpYkDyUZsr+AO+V79BrYG55nAAoVfDAXH2h13KTlScM3a4JzXSVzBVv+LHcUC8Z2p3Lw7+F6j8yDresSASZI5QooYLtDrWstoqt2Ce8VQUYlmfzOvp6g8druki3gJq7/hMUCVhvLu0JB8PiIUD7vI9NEO6v4hHSO1gkx+rfqgH1kB1bFIIlE/Sr9lxVZnSb00imE1vVf1J3AubpKX/Bl4r+4BdQ23lL8yvPoqTh9t6syj2FyOk0mH5NTiuom0TqP1hfpjZ/n5q56cFBP8um9SV7ewtlBP2jkZgBFXZP/DmxMMzs2R7gvxf3jPZLEz2giApQxxkzF0S8ORXXNDB0mXtjI8WFY9o8WvMaz2nf/iNzYBX1wZXHvqsoBfHuWBwrBzEW6Led86uDEDaWlmOKKKPLCN2uvWoxIikVnE05VHXb+brr2lf5oQuzDb029YEr1qvHv7tq2e3vfi3Asdl9n0mFM0GoG3laXX220PpXxrdSgqEuUVoztvC4W8L9iXQ+imBGVECukIaqyStnRmLDH8nrn12QFtj7laXYEhRZPm5tvM2HbN4HtZPyRiU/vsS+VVYXjB3/P5K7HYtJRsqQTaCMj4HAKnOqvwqdKJFAEfTBUtghGwIDAQABo1UwUzBRBgNVHREBAf8ERzBFgkNacldpRUdPOG81aWdhVjBITFlTZnI2RHJIYlpUaXBSOGhtZ0kwWmtzLnNlbGYtc2lnbmVkLmdvYXV0aGVudGlrLmlvMA0GCSqGSIb3DQEBCwUAA4ICAQAjYxXqwkZl1tIrqgoKROhhP6x1HdW9BIBEBQqzW6IttV7WbvL6LtlLeKqxAUZE0OsYXEEAJ3hzrX99Atlberqd/TloYcRSEx17fhfuSU3MRwArfiPByiq4hhHJL64GkcqGclg+FvbFweKqcz6mQ1BCmmn+hF7Zk0negaNWAZU465xjhsGTR7LjwZZJZ3WslqzSKxubJz2wqSkh+Y+3WNrjkE8YdEOMXkttJLc79qtmZjSEwtuOn2ZaF1aLrMZQ1FY1sNDFuHvK+0SWZdkkZ8qG0xzPmfUhIT8FHmY8CzEPexKjydzdOOZ1CGUgYSKj+isIqzW6tPWM6NhBo515oPuBox0PR5yyu5ZxCswckk+wXhD7LgKNoVlO0pB4gkyp6CtGSVQmuzXwN3fKkL/x5qDMSJn7Tyu7XYnyNmanWkIEw2RYLaqPiyOHMyoKCBYRJ7/xSDkR9OjUwJoqy/L0eTKO4FJMh9NWpUvMw3Fpl4QRAjOsV2QWsTmd3nr/ngnnsJmz//AnoamDpWIJbquUbz7PYqIM14hOjvX/hgV7rD5wJEMkO0hBY52oInkHbw0dFWqewtLiUEmf+iPZZgP+YNRiV/5uTLg56b2J54Hu0R53CC6NjS8JD2VARPvzsGo3PWMlVrfTe0IvZZWyaSsH/kLICmMu3uCBZSNxVE+GBqqGoA=="
x5t	"REf0xSyPsgVlNP36JcxDZWWQ7gs"
x5t#S256	"rwap9MwRt-kwT1eFAaDH1nvlTjYwcl0xJCnS1xEhAKI"
```

I get Unauthorized now when accessing the application.

**Comment by phillf** [comment]
Further update:

If I remove the authorizations sections from middlewares.yml:

```
          Authorization:
            AssertClaims:
              - Name: "roles"
                AllOf: ["Traefik - Admins"]
```

I can access the Traefik dashboard perfectly fine. Not sure what's going on.
