### ISSUE TITLE
After successfull login redirect is not working

### ISSUE THREAD

**Issue by zarnautovic** [sevensolutions/traefik-oidc-auth#32]
Hi,

First I want to say that project is great, and after playing around with zitadel and oauth2-proxy for 2 days with multiple trial and errors this just works and now I dont need another service.

But I have one issue, after login redirect is not working.

this is my middleware setup:

```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oidc-auth
  namespace: traefik
spec:
  plugin:
    traefik-oidc-auth:
      provider:
        url: "https://zitadel.mydomain"
        clientId: "clientId"
        usePkce: true
      secret: "secret"
      scopes: 
        - "openid"
        - "profile"
        - "email"
```

I am trying to protext traefik dashboard and I apply this middleware and that part work like a charm, but redirect is not working.

When I open network tab after login i can see two requests both with 302 status code:
POST ON https://zitadel.mydomain/ui/login/mfa/u2f/verify
GET ON https://zitadel.mydomain/oauth/v2/authorize/callback?id=300474110239049093

If I take url from second request and paste it in new tab redirect works.

in Zitadel I have project with app that have redirect uri:  https://traefik.mydomain/oidc/callback

**Comment by sevensolutions** [comment]
Thx @zarnautovic,
your redirect url config in ZITADEL looks correct.

What i've tried:

```yml
middlewares:
    oidc-auth:
      plugin:
        traefik-oidc-auth:
          LogLevel: DEBUG
          Provider:
            UrlEnv: "PROVIDER_URL"
            ClientIdEnv: "CLIENT_ID"
            UsePkce: true
          Scopes: ["openid", "profile", "email"]

  routers:
    dashboard:
      entryPoints: ["web"]
      rule: "Host(`dashboard.localhost`)"
      service: dashboard@internal
      middlewares: ["oidc-auth@file"]
    dashboard-api:
      entryPoints: ["web"]
      rule: "Host(`dashboard.localhost`) && PathPrefix(`/api`)"
      service: api@internal
      middlewares: ["oidc-auth@file"]
```

In ZITADEL i've whitelisted `http://dashboard.localhost:9080/oidc/callback`.

Now if i navigate to `http://dashboard.localhost:9080` in the browser i get redirected to ZITADEL and after login i get redirected back to `http://dashboard.localhost:9080`, showing the traefik dashboard.

What is your router config?
