### ISSUE TITLE
Error while parsing Provider.Url: invalid empty url

### ISSUE THREAD

**Issue by droplet-js** [sevensolutions/traefik-oidc-auth#33]
```yaml
services:

  traefik:
    container_name: traefik
    image: ghcr.io/traefik/traefik:v3.2.3
    restart: unless-stopped
    hostname: traefik
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/etc/traefik/acme
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
    command:
      - "--global.sendanonymoususage=false"
      - "--global.checknewversion=false"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--api.debug=false"
      - "--log.level=INFO"
      - "--log.format=common"
      - "--accesslog=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL:-traefik@traefik.com}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme-v2.json"
      - "--certificatesresolvers.letsencrypt.acme.keyType=EC384"
      - "--certificatesresolvers.letsencrypt.acme.preferredChain=ISRG Root X1"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      # Middleware traefikoidcauth
      - "--experimental.plugins.traefikoidcauth.modulename=github.com/sevensolutions/traefik-oidc-auth"
      - "--experimental.plugins.traefikoidcauth.version=v0.4.1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.gzip.compress=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${SERVER_DOMAIN:-localhost}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=gzip"

  dex:
    container_name: dex
    image: ghcr.io/dexidp/dex:v2.41.1
    restart: unless-stopped
    hostname: dex
    extra_hosts:
      - host.docker.internal:host-gateway
    configs:
      - source: dex_config
        target: /etc/dex/config.docker.yaml
    volumes:
      - dex_data:/var/dex
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.dex.loadbalancer.server.port=5556"
      - "traefik.http.routers.dex.service=dex"
      - "traefik.http.routers.dex.rule=Host(`dex.${SERVER_DOMAIN:-localhost}`)"
      - "traefik.http.routers.dex.entrypoints=websecure"

  whoami:
    container_name: whoami
    image: ghcr.io/traefik/whoami:v1.10.3
    restart: unless-stopped
    hostname: whoami
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.routers.whoami.service=whoami"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${SERVER_DOMAIN:-localhost}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      # Middleware oidcauth
      - "traefik.http.middlewares.oidcauth.plugin.traefikoidcauth.provider.urlEnv=https://dex.${SERVER_DOMAIN:-localhost}/dex"
      - "traefik.http.middlewares.oidcauth.plugin.traefikoidcauth.provider.usepkce=true"
      - "traefik.http.middlewares.oidcauth.plugin.traefikoidcauth.provider.clientidEnv=${WHOAMI_DEX_CLIENT_ID?err}"
      - "traefik.http.middlewares.oidcauth.plugin.traefikoidcauth.provider.clientsecretEnv=${WHOAMI_DEX_CLIENT_SECRET?err}"
      # Middlewares
      - "traefik.http.routers.whoami.middlewares=oidcauth"

configs:
  dex_config:
    content: |
      issuer: https://dex.${SERVER_DOMAIN:-localhost}
      storage:
        type: sqlite3
        config:
          file: /var/dex/dex.db
      web:
        http: 0.0.0.0:5556
      connectors:
      - type: gitea
        id: gitea
        name: Gitea
        config:
          baseURL: https://gitea.${SERVER_DOMAIN:-localhost}
          clientID: ${DEX_GITEA_CLIENT_ID?err}
          clientSecret: ${DEX_GITEA_CLIENT_SECRET?err}
          redirectURI: https://dex.${SERVER_DOMAIN:-localhost}/callback
      oauth2:
        skipApprovalScreen: true
      staticClients:
      - id: ${WHOAMI_DEX_CLIENT_ID?err}
        name: Who Am I
        secret: ${WHOAMI_DEX_CLIENT_SECRET?err}
        redirectURIs:
        - https://whoami.${SERVER_DOMAIN:-localhost}/callback
```
