### ISSUE TITLE
Allow for sending the tokens to the upstream service

### ISSUE THREAD

**Issue by sevensolutions** [sevensolutions/traefik-oidc-auth#36]
Because of the encrypted cookies it is not possible anymore to get the access token in the upstream service.
I want to add an option to allow the use to pass these tokens to the upstream.

I think i will combine the `MapClaims`-API with this feature. Maybe like this:

Current:
```yml
Headers:
  MapClaims:
    - Header: "Blah"
      Claim: "MyValue"      
```

New:
```yml
Headers:
  - Name: "Blah"
    FromClaim: "MyValue"
  - Name: "Authorization"
    FromToken: "Bearer {{AccessToken}}"
```
