### ISSUE TITLE
Custom Token Sources

### ISSUE THREAD

**Issue by sevensolutions** [sevensolutions/traefik-oidc-auth#38]
### Support for custom token sources

Currently, the access token and entire session info is stored within the state-cookie. It can be configured like this:

```yml
traefik-oidc-auth:
  Provider:
    Url: "https://<YourIdentityProviderUrl>"
    ClientId: "<YourClientId>"
    ClientSecret: "<YourClientSecret>"
  StateCookie:
    Name: "Authorization"
```

The content of this cookie is encrypted and only meant to be used by the middleware itself.
It stores all the necessary session state. Therefore i'll maybe rename it to `SessionCookie`.

In addition I'll add two more options:

```yml
traefik-oidc-auth:
  Provider:
    Url: "https://<YourIdentityProviderUrl>"
    ClientId: "<YourClientId>"
    ClientSecret: "<YourClientSecret>"
  StateCookie:
    Name: "Authorization"
  AuthorizationHeader:
    Name: "Authorization"
  AuthorizationCookie:
    Name: "MyCustomAuthCookie"
```

`AuthorizationHeader` and `AuthorizationCookie` will be two new options. If configured and a request will contain the specified `AuthorizationHeader`, it's content will be interpreted as a plain-text access-token and validated instead of the `StateCookie`'s content.
This will also work if no session (`StateCookie`) exists.

If no `AuthorizationHeader` but an `AuthorizationCookie` is present on the request, it's content will be handled in the same way.
If neither of these two options are present, the `StateCookie` will be used.

Please note that refreshing these tokens in `AuthorizationHeader` or `AuthorizationCookie` is the external users responsibility.

### Configuration for unauthorized requests

As of now, the plugin will always redirect the user to the IDP, if the request is not authenticated (contains no `StateCookie`, `AuthorizationHeader`, or `AuthorizationCookie`).

When using machine-to-machine communication, this may be not a good idea. Instead, a direct 401 response would be better.
Therefore I'll add this new option.

```yml
traefik-oidc-auth:
  Provider:
    Url: "https://<YourIdentityProviderUrl>"
    ClientId: "<YourClientId>"
    ClientSecret: "<YourClientSecret>"
  UnauthorizedBehavior: "Challenge"
```

The default `UnauthorizedBehavior` will be `Challenge`. This means, the user will be redirected to the IDP, if he is not authenticated by one of the options described above.
But you can set this to `Unauthorized` and the user will received a 401 response instead of the redirection to the IDP.

Previously, a similar behavior could have been configured when setting a `LoginUri`.
Maybe I'll remove this indirect behavior and make it explicit. (Means: You would have to set `UnauthorizedBehavior` to `Unauthorized` explicitly).
