### ISSUE TITLE
Variables in custom Headers don't work

### ISSUE THREAD

**Issue by meytin1337** [sevensolutions/traefik-oidc-auth#45]
Unfortunately the variables in the custom headers don't seem to be evaluated.
I have the following middelware config:
```
  plugin:
    traefik-oidc-auth:
      Headers:
        - Name: "Authorization"
          Value: "{{`Bearer {{ .accessToken }}`}}"
        - Name: "X-Oidc-Username"
          Value: "{{`{{ .claims.personId }}`}}"
```
And whoami shows the following information:
![image](https://github.com/user-attachments/assets/4abb2758-f23b-4b79-a156-77851a7cba44)
