### ISSUE TITLE
Kubernetes sealed secrets

### ISSUE THREAD

**Issue by zarnautovic** [sevensolutions/traefik-oidc-auth#48]
Hi,

Is there a way to use kubernetes sealed secrets for secret and clientid values ?

I know plugin cant use sealed controller to get value, but I tried to create sealed secret for traefik deployment and resolve them on build to env variables to traefik pod, but still I didnt manage to refernce that raw value to plugin.

Is there a way to do this ?

**Comment by sevensolutions** [comment]
Hi @zarnautovic,
unfortunately i dont have that much experience with Kubernetes. Can you maybe provide me a sample deployment file to get traefik and the plugin up an running? Then i can try to get it running on Minikube.

Cant we do some templating in Kubernetes to get the value of the secret and inject it into the config?
Unfortuantely i dont know how these secrets work...

**Comment by zarnautovic** [comment]
Probably issues way will be to have something like clientIdEnv but for secret value (secretEnv).

I can give traefik container env variables from kube secrets, just need a way to reference that variable to OIDC plug-in.

**Comment by cdanis** [comment]
> Probably issues way will be to have something like clientIdEnv but for secret value (secretEnv).
> 
> I can give traefik container env variables from kube secrets, just need a way to reference that variable to OIDC plug-in.

If you can post your k8s manifests (or Helm chart values or whatever) I can take a look.

**Comment by cdanis** [comment]
> Is there a way to use kubernetes sealed secrets for secret and clientid values ?
> 
> I know plugin cant use sealed controller to get value, but I tried to create sealed secret for traefik deployment and resolve them on build to env variables to traefik pod, but still I didnt manage to refernce that raw value to plugin.

You can write a config like the following:

```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: toidcp
  namespace: traefik
spec:
  plugin:
    oidc:
      Provider:
        ClientId: urn:k8s:secret:toidcp:providerClientId
        ClientSecret: urn:k8s:secret:toidcp:providerClientSecret
      Secret: urn:k8s:secret:toidcp:pluginSecret
```

`urn:k8s:secret:{{name of the secret}}:{{key of the secret}}` will be resolved by Traefik as the value of the key inside the named secret (which must be in the same namespace as the middleware).
