### ISSUE TITLE
How to properly use `Headers`?

### ISSUE THREAD

**Issue by astappiev** [sevensolutions/traefik-oidc-auth#55]
Let's say I would like to imitate Forward Auth.

I expected, that I need to define the following `Headers` configuration:
```yaml
          Scopes: ["openid", "profile", "email", "groups"]
          Headers:
            - Name: "Remote-User"
              Value: "{{`{{ .claims.preferred_username }}`}}"
            - Name: "Remote-Email"
              Value: "{{`{{ .claims.email }}`}}"
            - Name: "Remote-Groups"
              Value: "{{`{{ .claims.groups }}`}}"
            - Name: "Remote-Name"
              Value: "{{`{{ .claims.name }}`}}"
```

But this results into
```text
Remote-Email: <no value>
Remote-Groups: <no value>
Remote-Name: <no value>
Remote-User: <no value>
```

I tried to investigate and used `Value: "{{`{{ .claims }}`}}"` to see what it consists of.

Which printed
```text
Remote-Claims: map[aud:traefik-oauth2 client_id:traefik-oauth2 exp:1.737289665e+09 iat:1.737288765e+09 iss:https://idm.example.com/oauth2/openid/client_id jti:<nil> nbf:1.737288765e+09 parent_session_id:4cbe2858-bf17-4523-820e-a16cc33b4965 scope:email groups openid profile session_id:5f6ca553-c475-4189-a16e-60cd65f0bf42 sub:5c55236d-1113-4764-9237-66de80483091]
```

I'm using kanidm and the setup I described in this [PR](https://github.com/sevensolutions/traefik-oidc-auth/pull/53).

Doesn't it work as expected, or am I wrong in what I'm doing?
