### ISSUE TITLE
Question - Shared client id, separate middleware assertclaims

### ISSUE THREAD

**Issue by undaunt** [sevensolutions/traefik-oidc-auth#88]
Hello,

I'm trying to figure out the most efficient way to structure access to my non-OIDC apps behind Pocket ID with Traefik and your plugin. I may be misunderstanding it though. Currently, in Pocket ID I have an app with a callback of `https://*.my.domain/oidc/callback` and my config within the Traefik dynamic file middlewares is as follows:

```
    oidc-auth:
      plugin:
        traefik-oidc-auth:
          LogLevel: DEBUG
          Secret: x
          Provider:
            Url: http://pocket-id:8080
            ClientId: x
            ClientSecret: x
            TokenValidation: IdToken
            UsePkce: false
          scopes: ["openid", "profile", "email", "groups"]
          # Explicitly set the callback URI so that the plugin uses an absolute URL.
          # This is the “absolute/host” approach from the callback-uri docs.
          #CallbackUri: https://id.my.domain/oidc/callback
          SessionCookie:
            Domain: ".my.domain"
          Authorization:
            AssertClaims:
              - Name: preferred_username
                AnyOf: ["me"]
          Headers:
            - Name: "Authorization"
              Value: "{{`Bearer {{ .accessToken }}`}}"
            - Name: "X-Oidc-Username"
              Value: "{{`{{ .claims.preferred_username }}`}}"
            - Name: "X-Oidc-Name"
              Value: "{{`{{ .claims.name }}`}}"
            - Name: "X-Oidc-Email"
              Value: "{{`{{ .claims.email }}`}}"
            - Name: "X-Oidc-Groups"
              Value: "{{`{{ .claims.groups }}`}}"
    oidc-auth-family:
      plugin:
        traefik-oidc-auth:
          LogLevel: DEBUG
          Secret: x
          Provider:
            Url: http://pocket-id:8080
            ClientId: x
            ClientSecret: x
            TokenValidation: IdToken
            UsePkce: false
          scopes: ["openid", "profile", "email", "groups"]
          SessionCookie:
            Domain: ".my.domain"
          Authorization:
            AssertClaims:
              - Name: groups
                AnyOf: ["me", "family"]
          Headers:
            - Name: "Authorization"
              Value: "{{`Bearer {{ .accessToken }}`}}"
            - Name: "X-Oidc-Username"
              Value: "{{`{{ .claims.preferred_username }}`}}"
            - Name: "X-Oidc-Name"
              Value: "{{`{{ .claims.name }}`}}"
            - Name: "X-Oidc-Email"
              Value: "{{`{{ .claims.email }}`}}"
            - Name: "X-Oidc-Groups"
              Value: "{{`{{ .claims.groups }}`}}"
    oidc-auth-all:
      plugin:
        traefik-oidc-auth:
          LogLevel: DEBUG
          Secret: x
          Provider:
            Url: http://pocket-id:8080
            ClientId: x
            ClientSecret: x
            TokenValidation: IdToken
            UsePkce: false
          scopes: ["openid", "profile", "email", "groups"]
          SessionCookie:
            Domain: ".my.domain"
          Headers:
            - Name: "Authorization"
              Value: "{{`Bearer {{ .accessToken }}`}}"
            - Name: "X-Oidc-Username"
              Value: "{{`{{ .claims.preferred_username }}`}}"
            - Name: "X-Oidc-Name"
              Value: "{{`{{ .claims.name }}`}}"
            - Name: "X-Oidc-Email"
              Value: "{{`{{ .claims.email }}`}}"
            - Name: "X-Oidc-Groups"
              Value: "{{`{{ .claims.groups }}`}}"
```

I then assigned one docker container the middleware of oidc-auth, and one of oidc-auth-family. I can access both without issue. If I simulate logging in as my wife, she cannot access the app behind oidc-auth, but if she logs into the oidc-auth-family app and then returns to the oidc-auth app, it lets her in and the logs show a session is present.

Is this approach feasible and I'm just doing something wrong, or should I move the user/group filtering upstream to Pocket ID and create 3 separate OIDC apps and manage permissions there and simply remove all of the AssertClaims from the middleware? Or some other solution?

Thanks for your insight!
