### ISSUE TITLE
🐛 Bug: Logout not working

### ISSUE THREAD

**Issue by adriaanh** [sevensolutions/traefik-oidc-auth#91]
### Reproduction steps

I have Pocket-ID configured with this plugin. I have the following relevant configuration with absolute callback-URL.
I can login. When I go to the /logout endpoint, I get the logout screen from Pocket-ID. When logged out, and I go back to the service, I still get access. The cookie is still present. When I delete the cookie, I'm logged out.
I tried setting a LogoutUri, but that didn't change anything.

```
http:
  middlewares:
    middlewares-oidc:
      plugin:
        traefik-oidc-auth:
          Secret: "SECRET"
          Provider:
            ClientID: "CLIENTID"
            ClientSecret: "CLIENTSECRET"
            Url: "POCKETID-URL"
            TokenValidation: "IdToken"
          CallbackUri: "https://oidc.example.com/callback"
          SessionCookie:
            Domain: ".example.com"
          Scopes: ["openid", "profile", "email", "groups"]
          Headers:
            - Name: "X-Oidc-User"
              Value: "{{`{{ .claims.preferred_username }}`}}"
            - Name: "X-Oidc-Groups"
              Value: "{{`{{ .claims.groups }}`}}"
            - Name: "X-Oidc-Email"
              Value: "{{`{{ .claims.email }}`}}"
            - Name: "X-Oidc-Name"
              Value: "{{`{{ .claims.name }}`}}"
  
  routers:
    auth:
      rule: "Host(`oidc.example.com`)"
      service: noop@internal
      middlewares: ["middlewares-oidc@file"]
```

### Expected vs actual behavior

I should expect that the cookie is deleted upon logout, but instead I see the cookie still being present.

### Environment and Version Numbers

* Traefik v3.2.1
* Plugin 0.7.0
* All docker

### Log Output

* No relevant logs

### Doing your homework

- [x] I have searched for similar bug reports and not found a similar one.

**Comment by sevensolutions** [comment]
Hi @adriaanh,
thx for reporting this. I had something similar in the past.

Can you please check the network logs in your Browser's dev console.
Do you get redirected to the callback-url after you've logged out from Pocket-ID?
And if yes, what is it returning?

**Comment by adriaanh** [comment]
I will check in the weekend. I'll keep you posted.

**Comment by adriaanh** [comment]
With the absolute CallbackUri configured without additional 'LogoutUri' as described in my first post, I see the following happening in a private browser window:
- I go to a service (whoami.domain.example), I need to login.
- I go to whoami.domain.example/logout, I get the Pocket-ID logout screen. 
- In the network logs I see a 302 to the login.domain.example/api/oidc/end-session?client=xxx&post_logout_redirect_uri=https://login.domain.example/callback&state=xxx, then 302 to login.domain.example/logout which is then 200
- I click on the Sign Out button, and then I am redirected to https://login.domain.example/login
- Looking in my cookies, I still see the cookie present.
- When I go back to the service (whoami.domain.example) I don't need to authenticate and are still logged in. In Cookies I still see the cookie, and I also see the custom headers still being send with the request. 
- When I go back to the login.domein.example I see that I'm not authenticated in Pocked-ID

When I configure a additional absolute LogoutUrl and PostLogoutRedirectUri, I even don't get the redirect to Pocket-ID or my logoutredirecturi, I will just see the 418-response from noob@internal. My configuration:

```
http:
  middlewares:
    middlewares-oidc:
      plugin:
        traefik-oidc-auth:
          Secret: "SECRET"
          Provider:
            ClientID: "CLIENTID"
            ClientSecret: "CLIENTSECRET"
            Url: "https://login.domain.example"
            TokenValidation: "IdToken"
          CallbackUri: "https://oidc.domain.example.nl/callback"
          LogoutUri: "https://oidc.domain.example.nl/logout"
          PostLogoutRedirectUri: "https://whoami.domain.example.nl"
          SessionCookie:
            Domain: ".domain.example"
          Scopes: ["openid", "profile", "email", "groups"]
          Headers:
            - Name: "X-Oidc-User"
              Value: "{{`{{ .claims.preferred_username }}`}}"
            - Name: "X-Oidc-Groups"
              Value: "{{`{{ .claims.groups }}`}}"
            - Name: "X-Oidc-Email"
              Value: "{{`{{ .claims.email }}`}}"
            - Name: "X-Oidc-Name"
              Value: "{{`{{ .claims.name }}`}}"
  
  routers:
    auth:
      rule: "Host(`oidc.domain.example.nl`)"
      service: noop@internal
      middlewares: ["middlewares-oidc@file"]
```
