### ISSUE TITLE
exchangeAuthCode: received bad HTTP response from Provider: {"error":"invalid_grant","error_description":"AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token.

### ISSUE THREAD

**Issue by nv202410** [sevensolutions/traefik-oidc-auth#93]
Dear SevenSolutions,

I updated the plugin to the latest version and idtoken works but now I have another issue.

I want to use OIDC to let users authenticate through Microsoft Entra ID before they can check the Traefik dashboard.

This is are my config files

dynamic.yml

_http:
  routers:
    dashboard:
      entryPoints:
        - "Dashboard"
      rule: Host(`proxy.domain.net`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      service: api@internal
      middlewares:
        - oidc-auth
      tls: {}_

_oidc-auth:
      plugin:
        traefik-oidc-auth:
          Loglevel: DEBUG
          Secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
          CallbackUri: "https://proxy.domain.net:8080/dashboard/"
          PostLoginRedirectUri: "/dashboard/#/http/routers"
          SessionCookie:
            domain: ".domain.net"
          Provider:
            Url: "https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/v2.0/"
            ClientId: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            ClientSecret: " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx "
            TokenValidation: "IdToken"
          Scopes: [ "openid", "profile", "email_"]

static.yml

_api:
  Dashboard: true
experimental:
  plugins:
    traefik-oidc-auth:
      moduleName: "github.com/sevensolutions/traefik-oidc-auth"
      version: "v0.7.0"
entryPoints:
  Dashboard:
    address: ":8080"_

when I visit the url https://proxy.domain.net:8080/dashboard/ I get forwarded to Microsoft Entra ID. The whole authentication process work fine but the PostLoginRedirectUri causes issues that I cant be forwarded to the webpage. I Used the DuckDuckGO browser and FireFox.

I get the following logs from Debug Mode:

WARN] [traefik-oidc-auth] State is missing, redirect to Provider
Feb 26 14:06:01 proxy.domain.net traefik[362289]: 2025-02-26 14:06:01 [WARN] [traefik-oidc-auth] State is missing, redirect to Provider
Feb 26 14:06:01 proxy.domain.net traefik[362289]: 2025-02-26 14:06:01 [INFO] [traefik-oidc-auth] Redirecting to OIDC provider...
Feb 26 14:06:01 proxy.domain.net traefik[362289]: 2025-02-26 14:06:01 [INFO] [traefik-oidc-auth] Redirecting to OIDC provider...
Feb 26 14:06:01 proxy.domain.net traefik[362289]: 2025-02-26 14:06:01 [DEBUG] [traefik-oidc-auth] AuthorizationEndPoint: https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/authorize
Feb 26 14:06:01 proxy.domain.net traefik[362289]: 2025-02-26 14:06:01 [DEBUG] [traefik-oidc-auth] AuthorizationEndPoint: https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/authorize
Feb 26 14:06:02 proxy.domain.net traefik[362289]: 2025-02-26 14:06:02 [INFO] [traefik-oidc-auth] Exchange Auth Code completed. Token: XXXXXXXXXXXXX *** REDACTED ***
Feb 26 14:06:02 proxy.domain.net traefik[362289]: 2025-02-26 14:06:02 [INFO] [traefik-oidc-auth] Exchange Auth Code completed. Token: XXXXXXXXXXXXX *** REDACTED ***
Feb 26 14:06:02 proxy.domain.net traefik[362289]: 2025-02-26 14:06:02 [DEBUG] [traefik-oidc-auth] Session stored. Id xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Feb 26 14:06:02 proxy.domain.net traefik[362289]: 2025-02-26 14:06:02 [DEBUG] [traefik-oidc-auth] Session stored. Id xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Feb 26 14:06:02 proxy.domain.net traefik[362289]: 2025-02-26 14:06:02 [INFO] [traefik-oidc-auth] Redirecting to https://proxy.domain.net:8080/dashboard/#/
Feb 26 14:06:02 proxy.domain.net traefik[362289]: 2025-02-26 14:06:02 [INFO] [traefik-oidc-auth] Redirecting to https://proxy.domain.net:8080/dashboard/#/
Feb 26 14:06:03 proxy.domain.net traefik[362289]: 2025-02-26 14:06:03 [ERROR] [traefik-oidc-auth] exchangeAuthCode: received bad HTTP response from Provider: {"error":"invalid_grant","error_description":"AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token. Trace ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx Correlation ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx Timestamp: 2025-02-26 14:06:03Z","error_codes":[54005],"timestamp":"2025-02-26 14:06:03Z","trace_id":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","correlation_id":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"}
Feb 26 14:06:03 proxy.domain.net traefik[362289]: 2025-02-26 14:06:03 [ERROR] [traefik-oidc-auth] exchangeAuthCode: received bad HTTP response from Provider: {"error":"invalid_grant","error_description":"AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token. Trace ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx Correlation ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx Timestamp: 2025-02-26 14:06:03Z","error_codes":[54005],"timestamp":"2025-02-26 14:06:03Z","trace_id":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","correlation_id":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"}
Feb 26 14:06:03 proxy.domain.net traefik[362289]: 2025-02-26 14:06:03 [ERROR] [traefik-oidc-auth] Exchange Auth Code: invalid status code
Feb 26 14:06:03 proxy.domain.net traefik[362289]: 2025-02-26 14:06:03 [ERROR] [traefik-oidc-auth] Exchange Auth Code: invalid status code

What is the reason that i cant use this for acces to Traefik Dashboard? Do I miss configurations?

I allow in Entra ID in permissions to retrieve the scope details and the CallBackUri is the same in Entra ID. Also IdToken is selected instead of AccessToken.

What do I miss or what is the reason why forwarding doesnt work. My browser says is could be related with cookies but im not sure.

**Comment by sevensolutions** [comment]
Hi @nv202410,

unfortunately, securing the traefik dashboard is a little bit tricky.
I also couldn't get it working on a sub-path but for a different reason.
So i think you can only use a sub-domain like `traefik.127.0.0.1.sslip.io` in my case. At least without some manual url-rewriting.

The only working config i can come up with is:

```yml
http:
  middlewares:
    oidc-auth:
      plugin:
        traefik-oidc-auth:
          LogLevel: DEBUG
          Provider:
            UrlEnv: "PROVIDER_URL"
            ClientIdEnv: "CLIENT_ID"
            ClientSecretEnv: "CLIENT_SECRET"
            UsePkce: true
          Scopes: ["openid", "profile", "email"]
  
  routers:
    dashboard:
      entryPoints: ["websecure"]
      tls: {}
      rule: "Host(`traefik.127.0.0.1.sslip.io`)"
      service: dashboard@internal
      middlewares: ["oidc-auth@file"]
    dashboard-api:
      entryPoints: ["websecure"]
      tls: {}
      rule: "Host(`traefik.127.0.0.1.sslip.io`) && (PathPrefix(`/api`) || PathPrefix(`/oidc/callback`))"
      service: api@internal
      middlewares: ["oidc-auth@file"]
```

The following things are important:
- Use HTTPS, because EntraID only supports HTTPS redirect urls
- Use the `dashboard@internal` service for the dashboard itself. It seems that this is doing some more internal magic
- You also need a route for the `/api` path, routing to the `api@internal` service.
- Make sure you don't forget to route the `/oidc/callback` url to the plugin.

I was testing this against my EntraID and it was working fine.

Btw: Setting `TokenValidation: IdToken` isn't necessary anymore as it now defaults to `IdToken` when the Provider URL starts with `https://login.microsoftonline.com`. But it's no problem to keep it to be explicit.
