### ISSUE TITLE
Traefik Logs: Verifying token: unable to read session cookie: named cookie not present despite working Authentication

### ISSUE THREAD

**Issue by lba-mwde** [sevensolutions/traefik-oidc-auth#96]
First of all, thank you for the great plugin. The issue is not really having an impact on functionality; I just do not understand why it's happening.

I have read the FAQ entry about redirect loops ( https://traefik-oidc-auth.sevensolutions.cc/getting-started/faq#i-get-stuck-in-a-redirect-loop-after-signing-in ), which describes the same log message, but I don't face a redirection loop.

### Traefik Configuration (traefik.yml)
```yaml
experimental:
  plugins:
    traefik-oidc-auth:
      moduleName: "github.com/sevensolutions/traefik-oidc-auth"
      version: "v0.7.0"
 ```
### Middleware Configuration (middleware.yml)
```yaml
http:
  middlewares:
    pocket-id:
      plugin:
        traefik-oidc-auth:
          Secret: '{{ env "POCKET_ID_SECRET" }}'
          Provider:
            Url: "https://id.foo.bar/"
            ClientId: "client-id"
            ClientSecretEnv: "POCKET_ID_CLIENT_SECRET"
            TokenValidation: "IdToken"
          Scopes: ["openid", "profile", "email"]
 ```
### Sample Traefik Labels
```yaml
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      # Web Service
      - "traefik.http.routers.radarr.rule=Host(`radarr.foo.bar`)"
      - "traefik.http.routers.radarr.entrypoints=https"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.middlewares=default-whitelist@file,pocket-id@file"
      - "traefik.http.routers.radarr.priority=1"
      # API Service
      - "traefik.http.routers.radarr-api.rule=(Host(`radarr.foo.bar`) && PathPrefix(`/api`))"
      - "traefik.http.routers.radarr-api.entrypoints=https"
      - "traefik.http.routers.radarr-api.tls=true"
      - "traefik.http.routers.radarr-api.middlewares=default-whitelist@file"
      - "traefik.http.routers.radarr-api.priority=3"
      - "traefik.docker.network=proxy"
```

## Environment Details
- Identity Provider: Pocket ID
- Access: All services via HTTPS with valid Let's Encrypt production certificates
